server:
  port: 8080
spring:
  application:
    name: api-user
---
spring:
  profiles: ide
  boot:
    admin:
      client:
        url: http://localhost:9090
        service-base-url: http://localhost:9090
        instance:
          prefer-ip: true
          service-base-url: https://zuul.cluster.camp/user
  datasource:
    url: jdbc:mysql://192.168.1.50:3306/spring?useUnicode=yes&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: spring
    password: spring1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    show-sql: true
  rabbitmq:
    host: localhost
    username: springcloud
    password: springcloud
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0
app:
  initial:
    data: false
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://eureka.cluster.camp/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
security:
  oauth2:
    resource:
      id: API-USER
      jwt:
        keyValue: -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA3t2SxlBs8BFtUwE684jy
          lLx8M49TnqPibkZwsWWKPDjcLZDa2yTaM9/wjtdyF5drpHf+Y6oG9ZQZb8pgMXaY
          M2JvW9FlEh61Ju/2yA5wr/PP0qQChwoq9Y8jrZViY5ZLo56BzSjUU89tKfn34UQJ
          zlWuOmZGuIadW6q9BP9HC6MhZ3yxMJy02iHeaHWjwCF0A3L+1BTglPsSlhp6Afx/
          uHX9oqcoiuZlBr6s7rSFsKkWQWJ1Chx/bI7I5LGApVjb4WU4s9dV6+zt1Z4j+52b
          5uX77igsAzNBXehcFMKfRO/htGdnoLzz1j+aPwqzod1IzZr2j89+g+9ruaK6CaWG
          VQIDAQAB
          -----END PUBLIC KEY-----
management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'