redis-ha:
  enabled: true

controller:
  enableStatefulSet: true

server:
  replicas: 2
  extraArgs:
    - --insecure
  env:
    - name: ARGOCD_API_SERVER_REPLICAS
      value: 2

repoServer:
  replicas: 2