apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-user
  namespace: springcloud
  labels:
    category: micro-service
spec:
  replicas: 1
  selector:
    matchLabels:
      api: api-user
  template:
    metadata:
      labels:
        api: api-user
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '8080'
        prometheus.io/path: '/actuator/prometheus'
    spec:
      containers:
        - name: api
          image: dockercamp/api-user:1.0.10-arm64v8
          ports:
            - containerPort: 8080
          env:
            - name: spring.profiles.active
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: active.profiles
            - name: spring.cloud.config.uri
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: config.host
            - name: eureka.client.serviceUrl.defaultZone
              valueFrom:
                configMapKeyRef:
                  name: clustercamp
                  key: eureka.host
---
apiVersion: v1
kind: Service
metadata:
  name: api-user
  namespace: springcloud
spec:
  selector:
    api: api-user
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: api-user
  namespace: springcloud
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: "PathPrefixStrip"
    external-dns.alpha.kubernetes.io/target: home.proxy.camp
spec:
  rules:
    - host: api-user.cluster.camp
      http:
        paths:
          - path: /
            backend:
              serviceName: api-user
              servicePort: 80